containers:
  scaler:
    namespace: quotascale-controller
    name: quotascale-controller
    repository: "some-private-registry.ing.com/quotascale-controller" # Build your own image with your own resize endpoint.
    tag: "latest"
    enableNodeScaling: false
    gitopsSecretName: ""
    quotaCheckInterval: "1m"
    quotaUpdateInterval: "1m"
