containers:
  scaler:
    namespace: quotascale-controller
    name: quotascale-controller
    repository: "ghcr.io/ssu-dcn/quotascale-controller"
    tag: "latest"
    enableNodeScaling: false
    nodeScalingMaxNodes: 3
    nodeScalingRepoURL: ""
    nodeScalingRepoBranch: ""
    nodeScalingRepoFilePath: ""
    nodeScalingGitUsername: ""
    nodeScalingGitPassword: ""
    gitopsSecretName: ""
    quotaCheckInterval: "1m"
    quotaUpdateInterval: "1m"
